### ISSUE TITLE
Keine Templateauswahl nach Installation unter 3.1.1

### ISSUE THREAD

**Issue by planepix** [cogizz/contao-modulesummarize#1]
Hi Christopher,

ich habe die Erweiterung eben einmal installiert unter einer 3.1.1.
Nach Datenbankupdate und Systemwartung kann ich ein Modul anlegen, aber erhalte keine Templateauswahl.
Bug oder Feature?

**Comment by cogizz** [comment]
Die Erweiterung ist noch nicht für 3.1.1 ... wir haben bisher noch 2.11.X im Einsatz.

**Comment by planepix** [comment]
;-) ich habe ab .. gelesen. Mea Culpa.
Danke dann warte ich :-)

**Comment by cogizz** [comment]
Nein leider momentan nur für 2.11.X, da ich es gerade im zuge eines 2.11 Projektes entwickelt habe. Aber wir können einen Deal machen, du checkst einmal ob es dir unter 2.11 gefällt und ich denke dabei mal über eine 3.1.1 Umsetzung nach. Viel dürfte da eigentlich nicht fehlen. Deal?
