### ISSUE TITLE
so siehts aus

### ISSUE THREAD

**Issue by planepix** [cogizz/contao-modulesummarize#2]
![modulesummarize-be](https://f.cloud.github.com/assets/1823889/756629/54c0e86e-e62d-11e2-88f9-c13c3f14a472.png)

**Comment by cogizz** [comment]
hast du den multicolumnwizard installiert?

**Comment by planepix** [comment]
tja, wer zu doof ist zu lesen... jupp jetzt alles da bis auf die Templateauswahl, das bleibt leer.

Systemwartung: check.
Cache leeren: check.
anderer Browser: check.

Im BE unter Templates finde ich die Templates, aber eben nicht in der Auswahl im Modul selbst.

![modulesummarize-be-2](https://f.cloud.github.com/assets/1823889/756665/bd089ade-e632-11e2-9cea-e9b41e506209.png)

**Comment by cogizz** [comment]
@planepix hast du den Modulordner nach dem Download auch in "modulesummarize" umbenannt, oder heißt der noch modulesummarize-master_c3?

Wenn ja, entweder den Ordner umbennen oder den Autoload-Creator ausführen.

**Comment by planepix** [comment]
hab das master vor dem ausführen des DB-Updates entfernt :-)
Hies nach dem Entzippen "modulesummarize-master".

Autoload-Creator: Modul angeklickt -> Autoload-Datei erstellen geklickt -> nun sind die Templates zur Auswahl da.
Danke Christopher.

**Comment by cogizz** [comment]
Perfekt! Wenn du das Master entfernst, brauchst du den Autoload-Creator eigentlich nicht mehr ausführen.

Vielen Dank fürs testen!
